remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
logo: /assets/img/logo.svg
site_favicon: /assets/img/favicon.ico
title: /dev/null talks
description: El sitio donde van las cosas que no van a ningún sitio
show_downloads: false
github:
- is_project_page: false
